### ISSUE TITLE
Does this support chat like intercom

### ISSUE THREAD

**Issue by vigneshrams** [robodisco/hightower#1]
Hi,

I am working for getting the chat like Intercom. Is it available already in this repo OR in Tincanz repo ?

How can i get it done any pointers or open source please direct me.

Thanks

**Comment by adamakhtar** [comment]
Hi @vigneshrams 

Tincanz is not being developed anymore. I may pick it up again in the future. This gem simply allows you to react to your users actions. If you find a gem that can do the messaging you want then its possible to use it with Hightower.

**Comment by vigneshrams** [comment]
Thanks a lot for the info. BTW do you know any pointer for implementing in app messaging like intercom or any open source ?

Thanks

**Comment by adamakhtar** [comment]
Unfortunately I dont know of any open source projects - you might however find something on rubytoolbox.com
