### ISSUE TITLE
Installed hightower unable to navigate to admin dashboard

### ISSUE THREAD

**Issue by vigneshrams** [robodisco/hightower#2]
Hi,

I used hightower gem and trying to check it functionalities but i am unable to view the dashboard.

i am running in localhost:3000

Thanks

**Comment by adamakhtar** [comment]
did you define an authorization method on your User model (or whatever class represents a user in your app)

e.g. 

``` ruby
class User
    def can_access_hightower?
        self.admin == true
    end
end
```

Then tell Hightower the name of the method in the hightower initializer

``` ruby
Hightower.authorization_method = :can_access_hightower?
```
